version: '3.7'
services:
  api:
    build:
      args:
        FLASK_DEBUG: ${FLASK_DEBUG:-0}
      context: api
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG:-0}
    volumes:
      - ./api/:/app
    ports:
      - 5000:5000

  frontend:
    build:
      args:
        NODE_ENV: development
      context: frontend
      target: development
    environment:
      DIST_DIR: /app/public
      API_URL: http://localhost:5000
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:3000
